name = "LapackExtra"
uuid = "de2d2ae4-ecc6-4314-b1bd-8d868446ad67"
authors = ["Kyungmin Lee <kyungmin.lee.42@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]
